### ISSUE TITLE
missing to_openscenario function?

### ISSUE THREAD

**Issue by ntutangyun** [ErwindeGelder/ScenarioDomainModel#2]
Hi,

thanks for providing this amazing scenario model. 

as title, I wonder how to export the scenario created here to the openScenario Format. 

Thanks.

**Comment by ErwindeGelder** [comment]
Hi,

Thank you for your support. Due to proprietary reasons, the `to_openscenario` function is not part of the public repository. If you would like to have more information, you can contact me via email.

Best regards,
Erwin
